### ISSUE TITLE
ESP8266_TN008f_NTP_Time_OLED_WIFI_Manager_Webserver_SSD1306 adds timezone offset everry second...

### ISSUE THREAD

**Issue by GerardZ** [G6EJD/ESP8266-NTP-time-on-an-OLED-witrh-WiFi-Manager#2]
ESP8266_TN008f_NTP_Time_OLED_WIFI_Manager_Webserver_SSD1306 adds the timezone offset every second when running. I saw you resolved it in the other two sketches, but not this one :) (after I figured exact the same way to resolve it myself). Maybe you want to resolve this:

void display_time(){ // Note Ticker called routines cannot get a time update using timeclient.update()!
  epoch          = epoch + 1;
  UTC_hours      = epoch % 86400 / 3600;
  if (DST) epoch = epoch + 3600; 
  epoch = epoch + int(TimeZone * 3600);
  calcDate();
  epoch = epoch - int(TimeZone * 3600);  // <- is missing there...

Very nice work !!!

**Comment by G6EJD** [comment]
Excellent spotting of the error and very many thanks for letting me know, I've now corrected the file. I've looked at those codes many times and I thought I'd tested them all thoroughly but mistakes always get through. Once again my thanks, Regards  Dave

**Comment by GerardZ** [comment]
Glad to be of help, though is just a little bit compared to your work. I am new to ESP8266 and this one got me really started, the issue forced me to dive into the code so that`s a good thing. Got a little smile when I saw your leap-year calculation, wishing I had your life-expectance :)

Thanks and regards, Gerard
