### ISSUE TITLE
Geting 2 screens

### ISSUE THREAD

**Issue by Pedotech** [G6EJD/ESP8266-NTP-time-on-an-OLED-witrh-WiFi-Manager#3]
Great project, I am eager to really see the clock, but I get a "screen" 
Dec
0-22485- Jan 70
2:0-12
(0-52) AM ((((counting down)))
DST-UKUSAAUS
Before this the oled very briefly displays what I think is the calendar and clock, but it is so rapid I don´t know is it is correct.
I don't really understand. I think it is some silly mistake of mine.
Thanks for your help, I would love to see the clock ticking!

**Comment by G6EJD** [comment]
1. First off what is being displayed on the serial port. it should be saying connected to an IP address?
2.  Does it say Webserver started...
3. Can you connect your browser to the IP address and does it respond? e.g. http://192.168.0.22/

**Comment by G6EJD** [comment]
IS the code your using as on Github 008g and no added Serial.println statements as the 1-sec ticker will not work with print statements in it.

I've just tried the code and it works fine with a Wemos DI and OLED, what parts are you using?

Are you using the display driver I provided as the Adafruit variant will not work with the small OLED from Wemos?

**Comment by Pedotech** [comment]
Hi
Thank you so much for your quick answer
On serial I am getting 
Connection result 3
Use this URL to connect 192.168.1.165
Webserver started

I am using all the code in https://github.com/G6EJD
ESP8266-NTP-time-on-an-OLED-with-WiFi-Manager <https://github.com/G6EJD/ESP8266-NTP-time-on-an-OLED-with-WiFi-Manager>

I removed my Adafruit original lib for SSD1306 and used mcauser’s /Adafruit
I am using Wemos D1R2 and an I2c OLED (working fine)

Thank you again for your help

Pedro

**Comment by G6EJD** [comment]
OK, I am assume it's still not working. This is what I did:
1. Downloaded the code from Github.
2. Extracted the 008g Version to a folder
3. Extracted and copied adafruit_ssd1306 to overwrite the current adafruit_ss1306 .cpp and h files
4. Compiled it uploaded it, works perfectly.

Now some questions for you:
1. What size display are you using? 1.3, 0.96 or 0.64" it is designed for the 0.64" Wemos OLED display
2. Are you using the correct adafruit_ssd1306 files, not the ones supplied by adafruit!

**Comment by Pedotech** [comment]
Hi David
I am using your code AN ESP8266 display accurate time using NTP on an OLED display, using the WiFi Manager to make a network connection last commit b09787b <https://github.com/G6EJD/ESP8266-NTP-time-on-an-OLED-with-WiFi-Manager/commit/b09787b408ba087d62e5be012d5a186270e18a5f> 6 Nov 2017
I am using an 0.96 Oled and the text is OK; I think I am getting some wrong time; do I have to comment some of your server choices.
If your using a smaller display do you get two pages as I do ?

Pedro

**Comment by G6EJD** [comment]
![img_1742](https://user-images.githubusercontent.com/6075568/34578373-9f9b624c-f17c-11e7-8128-54a4f4ac6325.JPG)
I only get one screen, your getting two screens because the 0.96" OLED is 128x64 and the 0.64" is 64x32.
1. Change the SSD1306 driver back to a working version for your setup. Test it.
2. Change the time source from :  NTPClient timeClient(time_udp);
to: NTPClient timeClient(time_udp,"us.pool.time.org", TimeZone * 3600, 60000); 

Choose a time server near you from: http://www.pool.ntp.org/en/

**Comment by G6EJD** [comment]
I presume you now have it running.

**Comment by Pedotech** [comment]
Thank you so much






Obter o Outlook para Android







On Fri, Jan 5, 2018 at 4:43 PM +0000, "G6EJD" <notifications@github.com> wrote:












I presume you now have it running.
