### ISSUE TITLE
if (millis() % 60000)

### ISSUE THREAD

**Issue by seurat-atreides** [G6EJD/ESP8266-NTP-time-on-an-OLED-witrh-WiFi-Manager#7]
Hi David,
I'd like to know what  you're intending to accomplish with the logic expression inside the loop().
Regards,
Seurat-Atreides

**Comment by G6EJD** [comment]
if (millis() % 60000) UpdateLocalTime();

Only occurs when millis() modulus 60000 = 1 or True and so it updates the time every minute!

**Comment by seurat-atreides** [comment]
(millis() % 60000) will always yield TRUE because the operation only yields FALSE when (millis() % 60000) = 0. Chances are this is never going to occur.
Therefore, UpdateLocalTime() is being called once in every loop. Look at the Serial monitor output; UpdateLocalTime() is being called once every loop() run which is required to update the display value.
Even negating the logic won't guarantee that (!(millis() % 60000)) will return TRUE.
